# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: observatory-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: observatory

  adminer:
    image: adminer
    container_name: observatory-adminer
    restart: always
    ports:
      - "8081:8080"